### PR TITLE
fix: `ConnectionState. _activity` in `client.change_presence`

### PR DESCRIPTION
**Pull request by leestarb**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

fix for
```
await client.change_presence(status=Status.INVISIBLE)
```
```
-->
  File "...\BDBot_loops_.py", line 162, in case_loop_status
    await client.change_presence(status=Status.INVISIBLE)
  File "...\Python310\lib\site-packages\dis_snek\client.py", line 1543, in change_presence
    await self._connection_state.change_presence(status, activity)
  File "...\Python310\lib\site-packages\dis_snek\state.py", line 137, in change_presence
    activity = self._activity if self._activity else []
AttributeError: 'ConnectionState' object has no attribute '_activity'
```

This on the other hand works
```
await client.change_presence(status=Status.INVISIBLE, activity=Activity(type=ActivityType.LISTENING, name="a"))
```

## Changes

remove unnecessary check

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by benwoo1110** [comment]
Merge conflicts needs to be solved first 😅
