### PR TITLE
Private channel fix

### LINKED ISSUE #497: [BUG] `Message.reply` fails in DMs + no channel for DMs
**Describe the bug**
I know, weird wording, but the first part is what people run into 90% of the time, while the second is the *actual* underlying issue.

Anyways, users have recently told us that trying to reply to a message in DMs fails. Furthermore, the error message shows that it's unable to get the DM channel needed in the first place, as it returns `None`.

It was reported that this was working fine in earlier versions, so there may be a regression here. I am unsure if this bug appears in the `master` branch, but it does for sure in `dev`.

**To Reproduce**
```python
After updating I am getting an error upon DM replies. The repro would be doing something like 

```python
@listen()
async def on_message_create(self, event: MessageCreate) -> None:
    if not event.message.guild:
        await event.message.reply("Pong!")
```

**Expected behaviour**
The user to be DMed 'Pong!'

Instead, we get a basic "'NoneType' has no attribute 'send'."

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Another potential fix for the forbidden channel issue. This time its a dummy channel object. I appreciate this isnt an ideal solution, but as this dummy channel object is never cached, it won't cause future api calls to be skipped. 

## Changes

- On forbidden, `cache.fetch_channel` will generate a `BaseChannel` of type MISSING with only the ID field populated
- If a user needs a DM channel reference, and its not cached, a dummy DM channel object will be instantiated 

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
Unless there are any objections this PR will be merged. My tests shows it resolves the aforementioned issue
