### PR TITLE
fix: Update flake8-bandit to 3.0.0 to fix bug

### PR DESCRIPTION
**Pull request by zevaryx**
## What type of pull request is this?

- [ ] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change
- [x] Utility change

## Description

`flake8-bandit ~= 2.1` has a bug due to a newer release of Bandit:

```
TypeError: BanditNodeVisitor.__init__() missing 1 required positional argument: 'metrics'
```

This PR fixes this issue by bumping the version to 3.0

## Changes

- Update flake8-bandit in pre-commit config

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by zevaryx** [comment]
Failed checks aren't related to my changes? This only changed the pre-commit config

**Comment by LordOfPolls** [comment]
The failure is from @artem30801 
https://github.com/Discord-Snake-Pit/Dis-Snek/commit/45345709ea8b73190a3a312651b8d176037c0b75

They are aware of it
