### PR TITLE
Allow string footers

### LINKED ISSUE #428: [Feat] Support raw strings in Embed.footer
**Describe the bug**
When you set the footer in the embed class you get an erorr.

**To Reproduce**
The code you used to produce this bug, must be in a code-block:
```py
@dis.message_command("embed")
async def embed(ctx: dis.MessageContext):
    await ctx.send(embed=dis.Embed(title="test", description="test", footer="test"))
```

**Expected behaviour**
Send the embed

**Traceback**
```
Traceback (most recent call last):
  File "D:\Dis-Snek\dis_snek\client\client.py", line 1418, in _dispatch_msg_commands
    await self._run_message_command(command, context)
  File "D:\Dis-Snek\dis_snek\client\client.py", line 1289, in _run_message_command
    return await command(ctx)
  File "D:\Dis-Snek\dis_snek\models\snek\command.py", line 102, in __call__
    await self.call_callback(self.callback, context)
  File "D:\Dis-Snek\dis_snek\models\snek\command.py", line 146, in call_callback
    return await callback()
  File "D:\Dis-Snek\bot.py", line 10, in embed
    await ctx.send(embed=dis.Embed(title="test", description="test", footer="test"))
  File "<attrs generated init dis_snek.models.discord.embed.Embed>", line 16, in __init__
    _setattr('footer', __attr_converter_footer(footer))
  File "D:\Dis-Snek\dis_snek\client\utils\converters.py", line 56, in optional_converter
    return converter(val)
  File "D:\Dis-Snek\dis_snek\client\mixins\serialization.py", line 67, in from_dict
    return cls(**cls._filter_kwargs(data, cls._get_init_keys()))
  File "D:\Dis-Snek\dis_snek\client\mixins\serialization.py", line 36, in _filter_kwargs
    return {k: v for k, v in kwargs_dict.items() if k in keys}
AttributeError: 'str' object has no attribute 'items
```

### PR DESCRIPTION
**Pull request by LordOfPolls**
## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Allows for users to pass dictionaries, raw strings, and EmbedFooter objects when creating embeds

Resolves #428 

## Changes

- Created a new converter in EmbedFooter that handles the above

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

### CODE REVIEW

**Comment by LordOfPolls** [comment]
```python
@message_command()
async def test_embed(ctx: MessageContext):
    await ctx.send(embeds=Embed("Test string", footer="Test"))
    await ctx.send(embeds=Embed("Test Object", footer=EmbedFooter("Test")))
    await ctx.send(embeds=Embed("Test dict", footer={"text": "Test", "icon_url": None}))
```
image

**Review by silasary — APPROVED** [review]
